# Generated by Django 5.1.1 on 2024-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
