# Generated by Django 5.1.1 on 2024-09-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_code'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='Orders',
        ),
    ]
